# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json bun.lockb ./
RUN bun install

# Copy rest of the source code
COPY . .

# Build the project using Vite
RUN bun run build

# Expose the default port if needed (adjust if the server listens on a port)
# EXPOSE 3000

# Run the MCP server
CMD ["bun", "run", "build/index.js"]
